"use client";
import { useEffect, useRef, useState } from "react";
import { createGame } from "./engine";
import type { GameApi, GameStatus, HudState } from "./types";

export default function VillaGame(){
  const canvasRef=useRef<HTMLCanvasElement>(null);const apiRef=useRef<GameApi|null>(null);const aim=useRef<{id:number|null,x:number,y:number}>({id:null,x:0,y:0});const move=useRef<number|null>(null);
  const [started,setStarted]=useState(false);const [hud,setHud]=useState<HudState>({health:100,ammo:30,reserve:120,remaining:6});const [status,setStatus]=useState<GameStatus>("playing");const [damage,setDamage]=useState(false);const [kills,setKills]=useState<string[]>([]);
  useEffect(()=>{const c=canvasRef.current;if(!c)return;const api=createGame(c,{onHud:setHud,onDamage:()=>{setDamage(true);setTimeout(()=>setDamage(false),90);},onKill:(k)=>setKills(v=>[k,...v].slice(0,3)),onStatus:setStatus});apiRef.current=api;return()=>api.destroy();},[]);
  const deploy=()=>{apiRef.current?.start();setStarted(true);setStatus("playing");};
  const joy=(e:React.PointerEvent<HTMLDivElement>)=>{if(move.current===null)move.current=e.pointerId;if(move.current!==e.pointerId)return;e.currentTarget.setPointerCapture?.(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,max=r.width*.33,len=Math.max(1,Math.hypot(x,y)),scale=Math.min(1,max/len);const jx=Math.max(-1,Math.min(1,x*scale/max)),jy=Math.max(-1,Math.min(1,y*scale/max));apiRef.current?.setJoystick(jx,jy);const k=e.currentTarget.querySelector(".joyKnob") as HTMLElement|null;if(k)k.style.transform=`translate(${x*scale}px,${y*scale}px)`;};
  const joyEnd=(e:React.PointerEvent<HTMLDivElement>)=>{if(move.current!==e.pointerId)return;move.current=null;apiRef.current?.setJoystick(0,0);const k=e.currentTarget.querySelector(".joyKnob") as HTMLElement|null;if(k)k.style.transform="translate(0px,0px)";};
  const aimStart=(e:React.PointerEvent<HTMLDivElement>)=>{aim.current={id:e.pointerId,x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture?.(e.pointerId);};
  const aimMove=(e:React.PointerEvent<HTMLDivElement>)=>{const a=aim.current;if(a.id!==e.pointerId)return;apiRef.current?.aimDelta(e.clientX-a.x,e.clientY-a.y);a.x=e.clientX;a.y=e.clientY;};const aimEnd=(e:React.PointerEvent<HTMLDivElement>)=>{if(aim.current.id===e.pointerId)aim.current.id=null;};
  const fireDown=(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.stopPropagation();apiRef.current?.setFiring(true);e.currentTarget.setPointerCapture?.(e.pointerId);};const fireUp=(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.stopPropagation();apiRef.current?.setFiring(false);};
  return <main className="gameShell"><canvas ref={canvasRef} className="gameCanvas"/><div className="vignette"/><div className={`damageFlash ${damage?"on":""}`}/><div className="hud"><div className="topbar"><div className="mission">VILLA RAID // CLEAR THE PROPERTY</div><div className="stats">HP {hud.health}<br/>AK 7.62&nbsp;&nbsp;{hud.ammo} / {hud.reserve}<br/>HOSTILES {hud.remaining}</div></div><div className="crosshair"/><div className="killfeed">{kills.map((k,i)=><div className="kill" key={`${k}-${i}`}>{k}</div>)}</div></div>
  {started&&status==="playing"&&<div className="controls"><div className="aimPad" onPointerDown={aimStart} onPointerMove={aimMove} onPointerUp={aimEnd} onPointerCancel={aimEnd}/><div className="joyBase" onPointerDown={joy} onPointerMove={joy} onPointerUp={joyEnd} onPointerCancel={joyEnd}><div className="joyKnob"/></div><button className="fireButton" onPointerDown={fireDown} onPointerUp={fireUp} onPointerCancel={fireUp}>FIRE</button><button className="reloadButton" onPointerDown={e=>{e.preventDefault();e.stopPropagation();apiRef.current?.reload();}}>R</button><button className="jumpButton" onPointerDown={e=>{e.preventDefault();e.stopPropagation();apiRef.current?.jump();}}>JMP</button></div>}
  {!started&&<div className="startOverlay"><div className="startCard"><h1>Villa Raid</h1><p>Explore the pool terrace, main villa, kitchen, guesthouse and garden. Six armed guards patrol the property.</p><p><b>Phone:</b> left thumb moves, drag the right side to aim, hold FIRE. <b>Desktop:</b> WASD + mouse.</p><button className="deploy" onClick={deploy}>TAP TO DEPLOY</button></div></div>}
  {status!=="playing"&&started&&<div className="endOverlay"><div className="endCard"><h1>{status==="won"?"PROPERTY CLEARED":"MISSION FAILED"}</h1><p>{status==="won"?"All hostiles are down. The whole compound remains open to explore.":"You were taken out before the compound was cleared."}</p><button className="deploy" onClick={()=>location.reload()}>RESTART LEVEL</button></div></div>}<div className="rotateHint">Landscape recommended</div></main>;
}
